version: '3.4'
services:
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: docs
    image: gruntwork-docs
    volumes:
      - /usr/src/docs/node_modules
      - .:/usr/src/docs
    ports:
      - 8080:8000
